FROM node:18 AS builder
WORKDIR /vault
COPY frontend/package.json ./
COPY frontend/package-lock.json ./
RUN npm install
COPY frontend/tsconfig.json ./
COPY frontend/public ./public
COPY frontend/src ./src
RUN npm run build

FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /vault/build .
EXPOSE $PORT
ENTRYPOINT ["nginx", "-g", "daemon off;"]
