version: '3.9'

services:
  exeal-vault-backoffice:
    image: exeal-vault-backoffice
    build:
      context: .
      dockerfile: Dockerfile-backoffice
    container_name: exeal-vault-backoffice
    restart: always
    ports:
      - "${BACKOFFICE_PORT}:${BACKOFFICE_PORT}"
    environment:
      PORT: "${BACKOFFICE_PORT}"
    networks:
      - backoffice-and-frontend-network
      - backoffice-and-java-library-network

  exeal-vault-java-library:
    image: exeal-vault-java-library
    build:
      context: .
      dockerfile: Dockerfile-java-library
    container_name: exeal-vault-java-library
    restart: always
    ports:
      - "${JAVA_LIBRARY_PORT}:${JAVA_LIBRARY_PORT}"
    environment:
      PORT: "${JAVA_LIBRARY_PORT}"
    networks:
      - backoffice-and-java-library-network

  exeal-vault-frontend:
    image: exeal-vault-frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: exeal-vault-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      PORT: "${FRONTEND_PORT}"
    networks:
      - backoffice-and-frontend-network

networks:
  backoffice-and-java-library-network:
    driver: bridge
  backoffice-and-frontend-network:
    driver: bridge
