name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy-artifact:
    name: deploy-artifact
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backoffice image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-backoffice
          push: true
          tags: adrianlzgi/exeal-vault:exeal-vault-backoffice:latest

      - name: Build and push java-library image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-java-library
          push: true
          tags: adrianlzgi/exeal-vault:exeal-vault-java-library:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-frontend
          push: true
          tags: adrianlzgi/exeal-vault:exeal-vault-frontend:latest
